services:
  - type: web
    name: ser-streamlit-app
    env: python
    buildCommand: ""
    startCommand: streamlit run gui_app.py --server.port $PORT --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10